service: match-confirmation-api

frameworkVersion: "3"
useDotenv: true

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'

custom:
  webpack:
    includeModules: true
    packagerOptions:
      scripts:
        - npx prisma generate
        - find . -name "libquery_engine-*" -not -name "libquery_engine-rhel-openssl-*" | xargs rm
  serverless-offline:
    httpPort: 5000
    ignoreJWTSignature: true
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}
    apiKey: ${env:NEW_RELIC_API_KEY}
    cloudWatchFilter: "*"
    nrRegion: 'eu'
    enableFunctionLogs: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION}
  httpApi:
    metrics: true
    cors: true
    authorizers:
      auth:
        type: request
        functionName: auth
        identitySource: $request.header.Authorization
  environment:
    JWT_SECRET: ${env:JWT_SECRET}
    DATABASE_URL: ${env:DATABASE_URL}
    LAMBDA_MATCH_URL: ${env:LAMBDA_MATCH_URL}
    ZENDESK_SUBDOMAIN: ${env:ZENDESK_SUBDOMAIN}
    ZENDESK_API_USER: ${env:ZENDESK_API_USER}
    ZENDESK_API_TOKEN: ${env:ZENDESK_API_TOKEN}
    TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
    TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN}
    TWILIO_MESSAGING_SID: ${env:TWILIO_MESSAGING_SID}

functions:
  auth:
    handler: handler.auth

  sign:
    handler: handler.sign
    events:
      - httpApi:
          path: /sign
          method: GET

  feature-flag:
    handler: handler.featureFlag
    events:
      - httpApi:
          path: /feature-flag
          method: GET
          authorizer:
            name: auth
            type: request

  createConfirmation:
    handler: handler.createConfirmation
    timeout: 30
    events:
      - httpApi:
          path: /create-confirmation
          method: POST
          authorizer:
            name: auth
            type: request

  handleAnswer:
    handler: handler.handleAnswer
    timeout: 30
    events:
      - httpApi:
          path: /handle-answer
          method: POST
  
  expire:
    handler: handler.expire
    timeout: 30
    events:
      - httpApi:
          path: /expire
          method: POST

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-newrelic-lambda-layers
